### ISSUE TITLE
Laser does not produce a low power dot for alighnment

### ISSUE THREAD

**Issue by AndrewLShaw** [FABtotum/fabui-colibri#41] opened 2017-03-01 17:37 UTC
Before a laser engrave begins, during the 'Getting Ready' phase. The head can be moved around and the height adjusted but there is no laser dot to guide the placement of the head on the target material.

**Comment by daniel-fabteam** [comment] 2017-03-03 16:58
We have released a new update. Laser functionality is moved to a laser plugin.
The issue is fixed in the laser plugin.
You will need to download it from the `Plugin -> Online` section and activate it. 
There should be a new menu item in `Create` and Projectmanager will recognize laser gcode and show **Engrave** action next to them.

**Closed by daniel-fabteam** 2017-03-03 16:58 UTC
Labels: missing feature
