### ISSUE TITLE
Nozzle hight calibration IMPOSSIBLE both up and down buttons only move the platform down

### ISSUE THREAD

**Issue by BramElderman** [FABtotum/fabui-colibri#86] opened 2017-03-12 20:03 UTC
My head kept on jamming in the platform when starting to print but when I do a Nozzle hight calibration setting a new hight is impossible since both buttons (up and down) only move the platform down... there is no way to calibrate...
For now the head jams into the platform at start,.. I quickly pauze and lower the platform since there is no way around...

NB when I asked if I want to store this new hight its does not store

**Comment by krios-fabteam** [comment] 2017-03-16 08:33
Which browser are you using?
Could you make a new fresh [SD card](http://update.fabtotum.com/colibri/armhf/images/sdcard_latest.zip) and check if the issue is fixed?

**Comment by christopherwit** [comment] 2017-03-26 16:00
I have the same issue in both IE11 and Firefox, but only when I set a move offset smaller then 0.5mm

**Comment by AndrewKillian** [comment] 2017-03-26 19:35
I'm having the same issue on Google Chrome

**Comment by krios-fabteam** [comment] 2017-03-28 07:23
It should be fixed in the last update
Once you confirm it's fixed close this issue.

**Comment by krios-fabteam** [comment] 2017-03-29 07:13
Does anybody can confirm this was fixed?

**Comment by AndrewKillian** [comment] 2017-03-29 11:21
I can confirm it's fixed

**Comment by krios-fabteam** [comment] 2017-03-29 12:04
Happy to hear it.
I close the issue

**Closed by krios-fabteam** 2017-03-29 12:04 UTC
