### ISSUE TITLE
jog controls pseudo classes don't work as intended

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/fabui-colibri#184] opened 2017-06-14 20:31 UTC
Please be aware that pseudo class .hover makes the jog buttons permanently grey(as if they are inactive) after a mouse hover event in Microsoft Edge. And speudo class .active isn't applied at all.

It seems Firefox doens't trigger the pseudo classes at all. The buttons don't change colours.

Internet Explorer refused to show the jog buttons at all so no clue what is going on there.

**Comment by daniel-fabteam** [comment] 2017-06-19 07:51
Is a duplicate of #32. We are working on fixing and.

IE is not going to be supported.

**Closed** 2018-04-04 10:35 UTC
Labels: duplicate
